services:
  app1:
    build: .
    image: inkogether:1.0
    environment:
      - APP_NAME=app1
      - PORT=3001
    ports:
      - "3001:3001"

  app2:
    build: .
    image: inkogether:1.0
    environment:
      - APP_NAME=app2
      - PORT=3002
    ports:
      - "3002:3002"

  app3:
    build: .
    image: inkogether:1.0
    environment:
      - APP_NAME=app3
      - PORT=3003
    ports:
      - "3003:3003"

  nginx:
    image: nginx:stable
    ports:
      - "3000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
      - app3

networks:
  default:
    driver: bridge
